# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UiMainWindow(object):
    def setupUi(self, UiMainWindow):
        UiMainWindow.setObjectName("UiMainWindow")
        UiMainWindow.resize(814, 373)
        self.upload_photo_button = QtWidgets.QPushButton(UiMainWindow)
        self.upload_photo_button.setGeometry(QtCore.QRect(20, 20, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(10)
        self.upload_photo_button.setFont(font)
        self.upload_photo_button.setStyleSheet("background-color: rgb(172, 216, 255);\n"
"border-color: rgb(64, 134, 166);")
        self.upload_photo_button.setObjectName("upload_photo_button")
        self.photo = QtWidgets.QGraphicsView(UiMainWindow)
        self.photo.setGeometry(QtCore.QRect(20, 60, 81, 101))
        self.photo.setObjectName("photo")
        self.line = QtWidgets.QFrame(UiMainWindow)
        self.line.setGeometry(QtCore.QRect(0, 156, 118, 40))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(UiMainWindow)
        self.line_2.setGeometry(QtCore.QRect(103, 0, 40, 181))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.model_label = QtWidgets.QLabel(UiMainWindow)
        self.model_label.setGeometry(QtCore.QRect(15, 200, 85, 25))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(10)
        self.model_label.setFont(font)
        self.model_label.setStyleSheet("background-color: rgb(172, 216, 255);\n"
"border-color: rgb(64, 134, 166);")
        self.model_label.setObjectName("model_label")
        self.comboBox = QtWidgets.QComboBox(UiMainWindow)
        self.comboBox.setGeometry(QtCore.QRect(20, 240, 67, 22))
        self.comboBox.setObjectName("comboBox")
        self.line_3 = QtWidgets.QFrame(UiMainWindow)
        self.line_3.setGeometry(QtCore.QRect(101, 180, 40, 181))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.upload_video_button = QtWidgets.QPushButton(UiMainWindow)
        self.upload_video_button.setGeometry(QtCore.QRect(140, 20, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(10)
        self.upload_video_button.setFont(font)
        self.upload_video_button.setStyleSheet("background-color: rgb(172, 216, 255);")
        self.upload_video_button.setObjectName("upload_video_button")
        self.line_4 = QtWidgets.QFrame(UiMainWindow)
        self.line_4.setGeometry(QtCore.QRect(120, 156, 681, 40))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.start_search_button = QtWidgets.QPushButton(UiMainWindow)
        self.start_search_button.setGeometry(QtCore.QRect(140, 200, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(10)
        self.start_search_button.setFont(font)
        self.start_search_button.setStyleSheet("background-color: rgb(189, 255, 204);")
        self.start_search_button.setObjectName("start_search_button")
        self.progressBar = QtWidgets.QProgressBar(UiMainWindow)
        self.progressBar.setGeometry(QtCore.QRect(240, 240, 118, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.search_progress_label = QtWidgets.QLabel(UiMainWindow)
        self.search_progress_label.setGeometry(QtCore.QRect(260, 280, 54, 12))
        self.search_progress_label.setObjectName("search_progress_label")
        self.check_result_button = QtWidgets.QPushButton(UiMainWindow)
        self.check_result_button.setGeometry(QtCore.QRect(240, 320, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.check_result_button.setFont(font)
        self.check_result_button.setStyleSheet("background-color: rgb(33, 208, 54);\n"
"font: 75 9pt \"Adobe Devanagari\";\n"
"color: rgb(255, 255, 255);")
        self.check_result_button.setObjectName("check_result_button")
        self.line_5 = QtWidgets.QFrame(UiMainWindow)
        self.line_5.setGeometry(QtCore.QRect(440, 180, 40, 181))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.accuracy_label = QtWidgets.QLabel(UiMainWindow)
        self.accuracy_label.setGeometry(QtCore.QRect(480, 180, 80, 15))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(10)
        self.accuracy_label.setFont(font)
        self.accuracy_label.setObjectName("accuracy_label")

        self.retranslateUi(UiMainWindow)
        QtCore.QMetaObject.connectSlotsByName(UiMainWindow)

    def retranslateUi(self, UiMainWindow):
        _translate = QtCore.QCoreApplication.translate
        UiMainWindow.setWindowTitle(_translate("UiMainWindow", "Form"))
        self.upload_photo_button.setText(_translate("UiMainWindow", "上传人物照片"))
        self.model_label.setText(_translate("UiMainWindow", " 选择模型编号："))
        self.upload_video_button.setText(_translate("UiMainWindow", "上传视频"))
        self.start_search_button.setText(_translate("UiMainWindow", "开始检索"))
        self.search_progress_label.setText(_translate("UiMainWindow", "检索中..."))
        self.check_result_button.setText(_translate("UiMainWindow", "查看结果"))
        self.accuracy_label.setText(_translate("UiMainWindow", "模型准确率："))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UiMainWindow = QtWidgets.QWidget()
    ui = Ui_UiMainWindow()
    ui.setupUi(UiMainWindow)
    UiMainWindow.show()
    sys.exit(app.exec_())
